In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
import torch
from torch_geometric.data import Data
import awkward as ak
 
 
import torchUtils as gnn

In [2]:
dataset = gnn.Dataset('../data_csv')

In [3]:
from torch_geometric.loader import DataLoader

In [4]:
loader = DataLoader(dataset,batch_size=10)

In [5]:
it = iter(loader)

In [6]:
conv = gnn.layers.GCNConvMSG(11,2)

In [7]:
get_input = lambda g : (g.x,g.edge_index,g.edge_attr)

In [8]:
batch = next(it)

In [9]:
x, edge_index, edge_attr = get_input(batch)

In [10]:
x,edge_attr = conv(x,edge_index,edge_attr)

In [11]:
from torch_scatter import scatter_max 

In [12]:
batch

DataBatch(x=[94, 5], edge_index=[2, 402], edge_attr=[402, 1], batch=[94], ptr=[11])

In [13]:
score = edge_attr.sum(dim=-1)

In [14]:
arg_i = scatter_max(score, edge_index[0])[1]
arg_j = scatter_max(score, edge_index[1])[1]

In [15]:
edge_idx = torch.arange(edge_index.shape[1])


In [16]:
edge_mask = (edge_idx[...,None] == arg_i).any(dim=-1) | (edge_idx[...,None] == arg_j).any(dim=-1)

In [20]:
edge_attr,edge_index = edge_attr[edge_mask],edge_index[:,edge_mask]

In [26]:
edge_o = edge_attr[:,:2]

In [37]:
edge_mask.shape

torch.Size([402])

In [60]:
output

tensor([[-5.6596e-01, -4.5373e-01],
        [-7.9661e-01, -7.5942e-01],
        [-1.5305e+00, -2.1703e-01],
        [-1.9684e+00, -9.5477e-02],
        [-2.3182e+00, -1.7340e+00],
        [-2.6349e+00, -2.2453e+00],
        [-4.4590e+00, -1.1539e+00],
        [-5.3534e+00, -1.3525e+00],
        [-4.7012e+00, -4.1433e+00],
        [-5.0314e+00, -7.5877e-01],
        [-7.9661e-01, -7.5942e-01],
        [ 1.0000e+02, -1.0000e+02],
        [ 1.0000e+02, -1.0000e+02],
        [ 1.0000e+02, -1.0000e+02],
        [ 1.0000e+02, -1.0000e+02],
        [ 1.0000e+02, -1.0000e+02],
        [ 1.0000e+02, -1.0000e+02],
        [ 1.0000e+02, -1.0000e+02],
        [ 1.0000e+02, -1.0000e+02],
        [-1.5305e+00, -2.1703e-01],
        [ 1.0000e+02, -1.0000e+02],
        [ 1.0000e+02, -1.0000e+02],
        [ 1.0000e+02, -1.0000e+02],
        [ 1.0000e+02, -1.0000e+02],
        [ 1.0000e+02, -1.0000e+02],
        [ 1.0000e+02, -1.0000e+02],
        [ 1.0000e+02, -1.0000e+02],
        [-1.9684e+00, -9.547

In [34]:
edge_o

tensor([[-0.5660, -0.4537],
        [-0.7966, -0.7594],
        [-1.5305, -0.2170],
        [-1.9684, -0.0955],
        [-2.3182, -1.7340],
        [-2.6349, -2.2453],
        [-4.4590, -1.1539],
        [-5.3534, -1.3525],
        [-4.7012, -4.1433],
        [-5.0314, -0.7588],
        [-0.7966, -0.7594],
        [-1.5305, -0.2170],
        [-1.9684, -0.0955],
        [-2.3182, -1.7340],
        [-2.6349, -2.2453],
        [-5.0314, -0.7588],
        [-5.0314, -0.7588],
        [-5.0314, -0.7588],
        [-5.0314, -0.7588],
        [-0.5339, -0.1523],
        [-0.8878, -0.6958],
        [-1.8048, -0.5976],
        [-2.1370, -0.0795],
        [-2.6335, -2.4686],
        [-2.6456, -2.4606],
        [-3.4173, -0.2216],
        [-0.8878, -0.6958],
        [-2.1370, -0.0795],
        [-2.1370, -0.0795],
        [-3.4173, -0.2216],
        [-3.4173, -0.2216],
        [-3.4173, -0.2216],
        [-0.5540, -0.5269],
        [-1.1531, -0.1190],
        [-1.8276, -0.2795],
        [-2.6018, -0

In [18]:
trim = gnn.layers.TrimEdges(6)

In [19]:
edge_index,edge_attr = trim(x,edge_index,edge_attr)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [10]:
edge_attr.shape

torch.Size([3, 7])

In [11]:
edge_index

tensor([[0, 0, 1],
        [1, 2, 2]])